/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiOgSlugRouteImport } from './routes/api/og.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSlugRoute = ApiOgSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiOgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/posts/$slug': typeof PostsSlugRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/mcp' | '/api/og' | '/posts/$slug' | '/api/og/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/mcp' | '/api/og' | '/posts/$slug' | '/api/og/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/mcp'
    | '/api/og'
    | '/posts/$slug'
    | '/api/og/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiOgRoute: typeof ApiOgRouteWithChildren
  PostsSlugRoute: typeof PostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$slug': {
      id: '/api/og/$slug'
      path: '/$slug'
      fullPath: '/api/og/$slug'
      preLoaderRoute: typeof ApiOgSlugRouteImport
      parentRoute: typeof ApiOgRoute
    }
  }
}

interface ApiOgRouteChildren {
  ApiOgSlugRoute: typeof ApiOgSlugRoute
}

const ApiOgRouteChildren: ApiOgRouteChildren = {
  ApiOgSlugRoute: ApiOgSlugRoute,
}

const ApiOgRouteWithChildren = ApiOgRoute._addFileChildren(ApiOgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiOgRoute: ApiOgRouteWithChildren,
  PostsSlugRoute: PostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
